### ISSUE TITLE
Show build version on website

### ISSUE THREAD

**Issue by jtraglia** [flashbots/mev-boost-relay#110]
I think it would be really cool if we showed some type of hash on the relay's website that could be used to verify the relay matches what is found in this repository. For example, the sha256sum of the `mev-boost-relay` binary. This would only work if the build is reproducible though. [Reproducible Builds](https://reproducible-builds.org) is a good resource for getting that setup. Thoughts?

**Comment by metachris** [comment]
thanks for the submission, sadly it's that build hash is not verifiable :(
