### ISSUE TITLE
Is the internal API publicly accessible?

### ISSUE THREAD

**Issue by jtraglia** [flashbots/mev-boost-relay#119]
I don't see what makes this path internal. It appears to be configured the same as the other paths. What's preventing others from using this path? If it's public, anyone could blacklist builders.

https://github.com/flashbots/mev-boost-relay/blob/1c7fc7d9ae3cf215e960624cd1dade830847b511/services/api/service.go#L209

**Comment by metachris** [comment]
the assumption is that operators do the correct routing and firewalling in the infra.
but maybe this API should be disabled, and have an opt-in flag.

**Comment by jtraglia** [comment]
Okay so it's being handled in the infrastructure; that works. It seems to be configured properly on the mainnet relay. The following curl returns 200 status but no content. And yeah, making it opt-in may be a good idea.

```
curl -X GET https://boost-relay.flashbots.net/internal/v1/builder/0xa1dead01e65f0a0eee7b5170223f20c8f0cbf122eac3324d61afbdb33a8885ff8cab2ef514ac2c7698ae0d6289ef27fc
```

**Comment by metachris** [comment]
Thanks for checking :) Opened a PR to disable by default 👍

**Comment by jtraglia** [comment]
Great. Thanks!
