### ISSUE TITLE
Data API ProposerPayloadsDelivered implementation

### ISSUE THREAD

**Issue by aratz-lasa** [flashbots/mev-boost-relay#128]
Hello,

I'm opening this issue because of how `ProposerPayloadsDelivered` data API is implemented. Currently, in the [Data API specs of notion](https://flashbots.notion.site/Relay-API-Spec-5fb0819366954962bc02e81cb33840f5#417abe417dde45caaff3dc15aaae65dd) this is how the cursor parameter is described: 

> `cursor`: a slot cursor, where limit number of entries up until the cursor slot is returned (note only slot or cursor can be used)

So, this means that delivered payloads are returned up until the `cursor`, meaning that the `cursor` is the upper limit. Therefore, the returned entries should start at the bottom and go up until the `cursor` is hit or we reach `limit` amount of entries. But, in the current implementation the entries start at `cursor`, and go downwards until limit amount of `entries` are found.

So, is this a bug in the relay code or a change in the spec? Thank you!

**Comment by metachris** [comment]
Thanks for the report! What do you think makes the most sense? Maybe we should change `cursor` to `before_slot` 🤔

**Comment by metachris** [comment]
Updated the spec to make it clearer, based on your wording. thanks

**Comment by aratz-lasa** [comment]
Thanks for the fast response @metachris ! I think `cursor` it's a nice name, however, I would use the word _decreasing_ instead of _backwards_ to avoid confusion. Maybe something like "goes decreasing the slot number until...". What do you think?

**Comment by metachris** [comment]
sounds great, updated

**Comment by aratz-lasa** [comment]
Thanks, then I'm closing it
