### ISSUE TITLE
Blank response with status 200

### ISSUE THREAD

**Issue by itsdeka** [flashbots/mev-boost-relay#130]
Hello,

I am trying to build a custom implementation in Python of a block builder but I am facing an expected behaviour with the endpoint

**https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net/relay/v1/builder/blocks**

I receive an empty response with status code 200, what does this mean?

**Comment by metachris** [comment]
that is currently the expected response. please ask in our block builders self help group for more details: https://collective.flashbots.net/c/builders/14

**Comment by metachris** [comment]
Btw, I have not seen a successful submission. If you send me your builder pubkey i can look it up in the logs.

**Comment by itsdeka** [comment]
Thanks a lot Chris,
I'll sort out this first (https://github.com/flashbots/mev-boost-relay/issues/131) and then retry

Maybe this is the reason it silently fails

**Comment by itsdeka** [comment]
Hello Chris, I have submitted some blocks
Could you check if you see them and they are valid?

I have sent my builder pubkey to [chris@linuxuser.at](mailto:chris@linuxuser.at)

Thank you very much for all the help

**Comment by metachris** [comment]
Please post the pubkey publicly if you want to help in investigations. I'll look into improving block builder responses next week.

**Comment by itsdeka** [comment]
Sorry, here it is

0xb202aa8ea86faf39772142372a4c0c2276b72510fd5bb24f525cb872aba32f74eab188cfa2bed1daac92357acd327fae
