### ISSUE TITLE
From where to take the field 'prev_randao'

### ISSUE THREAD

**Issue by itsdeka** [flashbots/mev-boost-relay#131]
Hello, does someone know from where to take that field?

If I propose for slot X should I take the randao of slot X -1?

**Comment by metachris** [comment]
that's a question for our forum: https://collective.flashbots.net/c/builders/14

it comes from the previous block: https://github.com/flashbots/prysm/blob/develop-boost/beacon-chain/blockchain/execution_engine.go#L296-L301
