### ISSUE TITLE
Question: How to sign a corporate CLA with flashbots to contribute on behalf of my employer 

### ISSUE THREAD

**Issue by sambacha** [flashbots/mev-boost-relay#141]
This is in regards to this clause of the CLA agreement that is required to contribute back to mev-boost-relay:

https://github.com/flashbots/mev-boost-relay/blob/main/CONTRIBUTING.md#:~:text=that%20your%20employer%20has%20executed%20a%20separate%20corporate%20cla%20with%20flashbots.

**Comment by metachris** [comment]
That's not possible at the moment. Each contribution has to be signed off individually.

**Comment by sambacha** [comment]
> That's not possible at the moment. Each contribution has to be signed off individually.

Just going by what is laid out in these docs my guy, here is an example from mongodb: https://www.mongodb.com/legal/contributor-agreement

**Comment by sambacha** [comment]
Do not know why this was closed, their is an explicit requirement for a separate agreement to be signed for Employers.
