### ISSUE TITLE
feat: database migrations

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost-relay#203]
We want to have database migrations.

One consideration is that the base table name is configurable (with env var), and this doesn't seem to be supported by existing migration tooling (i.e. go-migrate).

What's the easiest and best way to add migrations?
* We could just manually add migrations as golang files
* These could be manually applied, without needing to store the migration status in the database itself

**Comment by srounce** [comment]
I think storing migration state in the DB would be sensible as it's directly pertinent to the rest of the stored state. Shifting the burden to the user to ensure they apply the correct migration(s) seems too risky and error prone for any advantage that would be gained. 

I reckon it would be useful to provide a top level `migrate` command to run any outstanding migrations, possibly with an additional argument(s) allowing the user to specify a direction and number of migrations to run. It would also be useful to have a `--migrate` flag on the `api` command to run them up to the latest version before starting the API server, this would make upgrades simply a matter of updating the image tag.

**Comment by metachris** [comment]
implemented in #224 🙏
