### ISSUE TITLE
Question about running services

### ISSUE THREAD

**Issue by DDiscua** [flashbots/mev-boost-relay#213]
I have cloned the repo and ran the docker-compose. But I'm having some questions

1.- Do I need to run a local PRYSM ?
2.- When I Run `go run . housekeeper --network sepolia --db postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable`

I'm getting the terminal error : zsh: no matches found: postgres://postgres:postgres@localhost:5432/postgres?sslmode=disable

**Comment by franciscodiazydiaz** [comment]
1. You need access to a beacon node, and you can use the client of your preference (Prysm is fine).
2. In zsh, the `?` needs to be escaped with `\`:
```zsh
go run . housekeeper --network sepolia --db postgres://postgres:postgres@localhost:5432/postgres\?sslmode=disable
```

**Comment by DDiscua** [comment]
I already setup the docker compose but still not working. Is there any change to get assistance by discord?
