### ISSUE TITLE
Replace types from go-boost-utils with types from Attestant

### ISSUE THREAD

**Issue by avalonche** [flashbots/mev-boost-relay#256]
Attestant / @mcdee has up-to-date types with a lot of tests: https://github.com/attestantio/go-eth2-client/tree/master/spec

Switching to the attestandtio types and deprecate the go-boost-utils types would reduce maintenance for future spec upgrades (e.g. upcoming Capella fork).

**Comment by metachris** [comment]
See also:
* https://github.com/flashbots/mev-boost/pull/411
* https://github.com/flashbots/mev-boost/issues/404

**Comment by metachris** [comment]
in progress, closing this issue
