### ISSUE TITLE
please return some text and different http status codes for the different return conditions

### ISSUE THREAD

**Issue by krasi-georgiev** [flashbots/mev-boost-relay#261]
the Submit block function returns `http.StatusOK` in most cases regardless of what happened in the handler

be good gentlemen and return some actual text and proper http status codes to notify the builder what actually happened

**Comment by Seyvick** [comment]
Que hago aki???.... No puedo entender nada.... Cómo comparto contenido o que tengo que hacer.... :(

**Comment by krasi-georgiev** [comment]
the actual reason for the failure

**Comment by metachris** [comment]
but which error cases specifically are you interested in?

**Comment by krasi-georgiev** [comment]
Can't remember now, but in general, it makes sense the responses follow the usual HTTP standards.

**Comment by metachris** [comment]
closing this issue for now, will reopen when there's specific examples of errors that would be more helpful
