### ISSUE TITLE
how to find my relay url ? 

### ISSUE THREAD

**Issue by ocoderr** [flashbots/mev-boost-relay#313]
i run a relay on my server, i want to konw how to find my relay url ? like  https://0xac6e77dfe25ecd6110b8e780608cce0dab71fdd5ebea22a16c0205200f2f8e2e3ad3b71d3499c54ad14d6c21b41a37ae@boost-relay.flashbots.net.   
the something like 0xac6....  how to find?

**Comment by metachris** [comment]
why do you want to run a relay?

you can find the URL by opening the website. but you need to define your URL manually, and the key is just the pubkey from the keypair you manually created.

**Comment by metachris** [comment]
perhaps a better place to ask your questions is in Flashbots Discord or the Flashbots forum
