### ISSUE TITLE
slot is too far into the future

### ISSUE THREAD

**Issue by Chaz27** [flashbots/mev-boost-relay#381]
If a slot was missed, then the relay's head slot will not be updated and will refuse to send a block for the next slot. The error "slot is too far into the future" is returned. Beacon client then reverts to locally produced block.

https://github.com/flashbots/mev-boost-relay/blob/171c1aa8cf2d2252d3d7a7cf5aa378fdddf8bcfc/services/api/service.go#L949

**Comment by metachris** [comment]
Yeah that's right. This is the check in getHeader: https://github.com/flashbots/mev-boost-relay/blob/cea4ba10399229d854877ed7563f03c83af59c30/services/api/service.go#L1096-L1100

Also there's another check in handleSubmitBlock, so no submissions would be accepted if the slot was missed: https://github.com/flashbots/mev-boost-relay/blob/cea4ba10399229d854877ed7563f03c83af59c30/services/api/service.go#L1566

I guess step 1 would be to use payloadAttributes for builder submissions, so they can get through in first place. cc/ @michaelneuder
