### ISSUE TITLE
Housekeeper failed to fetch validators, timeout

### ISSUE THREAD

**Issue by austonst** [flashbots/mev-boost-relay#412]
**Describe the bug**
After merging commits 273706c4b271796f90f36ad4c4f0f0b1f9c7642c to 6e47cf78a819ceef8367bf609138fd73f897e8ca (inclusive) to our branch and starting to test on Goerli, we encountered the following error on our housekeeper instance (an excerpt, showing two of our beacon nodes):
```time="2023-05-17T14:33:06Z" level=info msg="Querying validators from beacon node... (this may take a while)" headSlot=5652165 headSlotPos=6 lastUpdateSlot=0 method=updateKnownValidators service=relay/housekeeper version=
time="2023-05-17T14:33:11Z" level=error msg="failed to fetch validators" component=beaconClient error="client refused for http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500/eth/v1/beacon/states/head/validators?status=active,pending: Get \"http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500/eth/v1/beacon/states/head/validators?status=active,pending\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=relay/housekeeper uri="http://geth-prysm-0.geth-prysm.goerli.svc.cluster.local:3500" version=
time="2023-05-17T14:33:16Z" level=error msg="failed to fetch validators" component=beaconClient error="client refused for http://10.108.0.12:3500/eth/v1/beacon/states/head/validators?status=active,pending: Get \"http://10.108.0.12:3500/eth/v1/beacon/states/head/validators?status=active,pending\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" service=relay/housekeeper uri="http://10.108.0.12:3500" version=
time="2023-05-17T14:33:16Z" level=error msg="failed to fetch validators from all beacon nodes" error="all beacon nodes responded with error" headSlot=5652165 headSlotPos=6 lastUpdateSlot=0 method=updateKnownValidators service=relay/housekeeper version=
```

Running on an image whose most recent upstream commit is e6387e5cf7303a40ca999ab2515599c4b7f3c89e (older), we are able to successfully retrieve validators, e.g.:
`time="2023-05-17T14:49:21Z" level=info msg="received validators from beacon-node" durationFetchValidatorsMs=16121 headSlot=5652244 headSlotPos=21 lastUpdateSlot=0 method=updateKnownValidators numKnownValidators=457864 service=relay/housekeeper version=`

Fetching the full validator set on Goerli takes us 16-20s. About 32s on mainnet.

**Analysis**
273706c4b271796f90f36ad4c4f0f0b1f9c7642c implements a 5-second timeout for beacon client requests ([here](https://github.com/flashbots/mev-boost-relay/blob/273706c4b271796f90f36ad4c4f0f0b1f9c7642c/beaconclient/util.go#L22)). This seems to be the source of the issue: a recompiled version with this timeout set to 60s is able to fetch validators correctly as usual.

Is there a particular reason why this timeout was implemented, and does it need to be so short? Have other relays updated to run this code, and have they run into similar issues?

If a 5-second timeout is desirable in general, perhaps the housekeeper could override it (or use a different http.Client) for fetching validators.

**Which version are you using:**
- OS: Kubernetes/Docker
- Relay: Commits in question are described above, though note [our changes running on top](https://github.com/aestus-relay/mev-boost-relay/tree/redis-cluster). Config can be found [on our repo here](https://github.com/aestus-relay/kubernetes-config/blob/main/goerli/relay/housekeeper.yml).

**Comment by metachris** [comment]
Bundling into release v0.23, which also includes the fast validation change (which reduces validation load by ~50% - through ignoring submissions below the floor bid).
