### ISSUE TITLE
Expose non-validated bids in data API?

### ISSUE THREAD

**Issue by metachris** [flashbots/mev-boost-relay#422]
Currently the [bids data API](https://flashbots.github.io/relay-specs/#/Data/getReceivedBids) only shows bids that have been successfully validated.

Recently there have been validation improvements, which don't validate submissions below the floor bid. Any such ignored submissions are not exported through the data API because they haven't been simulated successfully.

Does this give an incomplete picture of the bids for a slot, and should all bids be exposed? Would that also mean exposing bids that didn't validate successfully?

**Comment by metachris** [comment]
Showing only the validated bids, as is right now, is probably cleaner, because it just exposes the bids that moved the top bid value.

**Comment by ralexstokes** [comment]
I'd consider this in line with the "archive" mode found in client software -- aim to have/support this feature but default to only keep a "reasonable" amount of data lying around

and if having all bids or anything beyond the status quo is unreasonable then it can fall into this bucket
