### ISSUE TITLE
Question: Relay Deployment Schedule

### ISSUE THREAD

**Issue by rkrasiuk** [flashbots/mev-boost-relay#427]
## Deployment Schedule

What are the deployment schedules for the relay on mainnet & testnets? Is it periodic by any chance? Is there a publicly available resource where I could access the current commit ref / version of the relay that's live, for instance, on sepolia?

**Comment by rkrasiuk** [comment]
Got it, thanks for quick response! Is testnet deployment triggered right after the PR is merged to main? How long does it usually take?

**Comment by metachris** [comment]
Usually PRs are tested in testnets before being merged to main. We also usually leave a comment on the PR once it's deployed to testnets

**Comment by rkrasiuk** [comment]
roger, thanks for the info!

**Comment by metachris** [comment]
To clarify a bit further - we are in the process of finding a stable release cadence.

Also our rollout process usually looks like this:
1. A PR has been reviewed and is ready for testing
2. we roll it out to our Sepolia relay
3. confirm it's working on Sepolia
4. we roll it out to our Goerli relay
5. confirm it's also working on Sepolia
6. after due time, we roll it out to our Mainnet relay
7. we merge the PR
8. cut a release after a few iterations and stable state
