### ISSUE TITLE
Capella Payload Signature Verification Fails for custom testnet

### ISSUE THREAD

**Issue by h4ck3rk3y** [flashbots/mev-boost-relay#507]
**Describe the bug**
I am trying to setup MEV components on top of the [kurtosis-tech/eth2-package](https://github.com/kurtosis-tech/eth2-package/pull/115) and I have got it to run but it only runs on a custom image with the following lines removed

https://github.com/flashbots/mev-boost-relay/blob/b7095834a40cb871074c48d02a8ade83e8ab65a3/services/api/service.go#L1263-L1272

If I let it stay I get a bunch of errors complaining about `"could not verify capella payload signature"`. Note that err is nil, the response is !ok.

**Steps to reproduce**

1. `kurtosis run github.com/kurtosis-tech/eth2-package@gyani/mev-capella-errors`
2. Open the MEV website; and wait for slot 96/128
3. Look at the logs for mev-relay-api

**Expected behavior**
The errors don't happen and the payload gets delivered

**Screenshots**
![image](https://github.com/flashbots/mev-boost-relay/assets/6670312/1ec205bf-95c0-4e24-896b-6b57358521f7)

**Which version are you using:**
- OSX - M1
- Kurtosis 0.81.5
- MEV Image - flashbots/mev-relay-api (latest)

@avalonche FYSA!

**Comment by h4ck3rk3y** [comment]
```
 kurtosis run github.com/kurtosis-tech/eth2-package '{"mev_type": "full", "mev_params": {"mev_relay_image": "flashbots/mev-boost-relay"}}'
```

You can use this to re-create the above issue as well! This doesn't depend on the custom branch.

**Comment by h4ck3rk3y** [comment]
This is the current image thats running by default - https://github.com/h4ck3rk3y/mev-boost-relay/pull/1/files

This disables the verification. You can ignore the `logging` I had added.

**Comment by ralexstokes** [comment]
are you supplying the correct value for `DomainBeaconProposerCapella`?

ideally we can run the stack without disabling signature verification

**Comment by h4ck3rk3y** [comment]
`DomainBeaconProposerCapella` seems to be based on CapellaFork and Genesis Validators Root, I went looking and I saw that the genesis validators root that I was setting had a `\n` at the end, fixing that fixed the problem. Thank you @ralexstokes

**Comment by dewindtk** [comment]
No way. Yall have no fking idea how much you saved me.
I have build t a devnet for my Bachelor's thesis and my genesis validator root configuration was missing, and this caused the capella verification to fail. Thanks so much for posting this,
@h4ck3rk3y you are such a savior no joke
