### ISSUE TITLE
How to get pending block's header via API ? 

### ISSUE THREAD

**Issue by nakedkoalacapital** [flashbots/mev-boost-relay#662]
I'd like to know if Flashbot & Agnostic relay support query of pending block header via API ? 

`baseUrl/eth/v1/builder/header/{slot}/{parent_hash}/{validator_pubkey}`

this URL works for ultrasound titan aeutus relays.   it doesn't work for either  https://agnostic-relay.net/ or  relay.flashbots.net as baseURL 

I have looked through the docs of either relays and did not find the answer.

**Comment by metachris** [comment]
that's the regular getHeader API that all relays support: https://ethereum.github.io/builder-specs/#/Builder/getHeader

that's how the validator receives the bid.

in case a relay doesn't have a bid for this slot and parent, it will send 204 as response status code
